name: CD

on:
  workflow_run:
    workflows: ["Docker"]
    types: ["completed"]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set kubeconfig
        run: |
          echo "${KUBE_CONFIG_B64}" | base64 -d > $HOME/.kube/config
        env:
          KUBE_CONFIG_B64: ${{ secrets.KUBE_CONFIG_B64 }}
      - name: Set image
        run: |
          sed -i "s|REPLACE_WITH_REGISTRY_IMAGE|${{ secrets.REGISTRY }}|g" k8s/deployment.yaml
      - name: Apply manifests
        run: |
          kubectl apply -f k8s/

